-- Drop tables if they exist to start fresh
DROP TABLE IF EXISTS telegram_links;
DROP TABLE IF EXISTS workspaces;
DROP TABLE IF EXISTS history;

-- Create history table
CREATE TABLE history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idea TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    result JSONB NOT NULL
);

-- Create workspaces table
CREATE TABLE workspaces (
    id TEXT PRIMARY KEY,
    idea TEXT NOT NULL,
    research_json JSONB NOT NULL,
    plan_json JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create telegram_links table
CREATE TABLE telegram_links (
    chat_id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    current_milestone_index INTEGER DEFAULT 0,
    linked_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_reminder_at TIMESTAMP WITH TIME ZONE
);


-- 1. Migrate workspaces table (add user_id referencing auth.users)
ALTER TABLE workspaces 
ADD COLUMN user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_workspaces_user_id ON workspaces(user_id);

-- Enable RLS on workspaces
ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;

-- Policy: Authenticated users can only read/write workspaces they own
CREATE POLICY workspaces_owner_policy ON workspaces
FOR ALL 
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);


-- 2. Migrate history table (add user_id referencing auth.users)
ALTER TABLE history 
ADD COLUMN user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_history_user_id ON history(user_id);

-- Enable RLS on history
ALTER TABLE history ENABLE ROW LEVEL SECURITY;

-- Policy: Authenticated users can only read/write history items they own
CREATE POLICY history_owner_policy ON history
FOR ALL 
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);


-- 3. Create a public user profiles table with a 1-to-1 relationship to auth.users
CREATE TABLE IF NOT EXISTS user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    display_name TEXT,
    avatar_url TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Enable RLS on user_profiles
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

-- Policies for user_profiles
CREATE POLICY "Allow public read access to user_profiles" ON user_profiles
    FOR SELECT USING (true);

CREATE POLICY "Allow users to update their own profile" ON user_profiles
    FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Create a trigger that automatically signs up a profile for new users
CREATE OR REPLACE FUNCTION handle_new_user_signup()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.user_profiles (id, display_name)
    VALUES (
        new.id, 
        COALESCE(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1))
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_signup_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION handle_new_user_signup();

