-- Drop tables if they exist to start fresh
DROP TABLE IF EXISTS mentor_chats;
DROP TABLE IF EXISTS telegram_links;
DROP TABLE IF EXISTS workspaces;
DROP TABLE IF EXISTS history;

-- Create history table
CREATE TABLE history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    idea TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    result JSONB NOT NULL
);

-- Create workspaces table
CREATE TABLE workspaces (
    id TEXT PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    idea TEXT NOT NULL,
    research_json JSONB NOT NULL,
    plan_json JSONB NOT NULL,
    is_saved BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create telegram_links table
CREATE TABLE telegram_links (
    chat_id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    current_milestone_index INTEGER DEFAULT 0,
    linked_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_reminder_at TIMESTAMP WITH TIME ZONE
);

-- Create mentor_chats table
CREATE TABLE mentor_chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- Create user_settings table if it doesn't exist
CREATE TABLE IF NOT EXISTS user_settings (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    theme TEXT DEFAULT 'dark',
    primary_model TEXT DEFAULT 'gemini',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add chat_history column to workspaces table if it doesn't exist
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS chat_history JSONB DEFAULT '[]'::jsonb;
